### ISSUE TITLE
Visensor_node build fails with newest OPENCV version

### ISSUE THREAD

**Issue by hwopereis** [ethz-asl/visensor_node#11]
Hi all,

I had some build issues with this package. The error generated was:

CMakeFiles/visensor_node.dir/src/visensor.cpp.o: In function `visensor::ViSensor::getRosStereoCameraConfig(visensor::SensorId::SensorId const&, sensor_msgs::CameraInfo_<std::allocator<void> >&, visensor::SensorId::SensorId const&, sensor_msgs::CameraInfo_<std::allocator<void> >&)':
visensor.cpp:(.text+0x6750): undefined reference to `cv::stereoRectify(cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int>, cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, double, cv::Size_<int>, cv::Rect_<int>*, cv::Rect_<int>*)'
collect2: error: ld returned 1 exit status

I solved this issue by adapting the CMakeLists file, line 40. I changed the following line to include the calib3d package
find_package(OpenCV REQUIRED COMPONENTS core highgui imgproc)
--> find_package(OpenCV REQUIRED COMPONENTS core highgui imgproc calib3d)

I'm not sure about the exact reason, but I think they were caused by the newest version of opencv  not standard including all packages.

**Comment by marco-tranzatto** [comment]
Fixed in PR #13
